[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "^0.0.3"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "^2.2.1"

[[constraint]]
  name = "github.com/fatih/color"
  version = "^1.7.0"
